apertif/apercal

libs/lib.py, modules/line_parallel.py, subs/qa.py
This removes an annoying warning at startup
=> Use pyfits

modules/prepare.py, subs/getdata_alta.py, subs/irods.py
The new file getdata_alta.py comes straight from https://github.com/cosmicpudding/altadata . We need a better way to sync, but for now a direct copy of one file is quite straightforward.
=> Use update getdata_alta from Vanessa

modules/default.cfg, modules/prepare.py
=> Make download from ALTA optional (for testing)

apercal/__init__.py, apercal/modules/ccal.py, apercal/modules/convert.py, apercal/modules/default.cfg, apercal/subs/calmodels.py, apercal/subs/misc.py, apercal/subs/msutils.py
This is a manual merge of the ccal branch into the CWL branch.
The code is a real mess, so at some point a gave up on cleaning and refactoring.
=> manually merge in ccal branch changes

cwl/steps/preflag.cwl
=> cwl/steps/preflag.cwl: InlineJavascriptRequirement is not needed

apercal/modules/convert.py
Fix a bug introduced in e4272377fb5e3edb4ec4677f77b2a245bcc55a2f leading to unknown drivecasa.
=> Fix forgotten drivecasa in refactor

apercal/libs/lib.py
This should make reading the logs a bit less painful
=> Log fewer casa output

apercal/modules/preflag.py
The bandpass in preflag was not properly applied; this should fix that.
=> Preflag bandpass

apercal/modules/ccal.py
This is an improvement on Danielle's fix where I identified the if/else block for setjy and moved it to be the first block in bandpass w/in cccal. Fixes #83 and removes concerns/issues with indents
=> Move setjy model to top of bandpass

apercal/modules/default.cfg, apercal/modules/preflag.py
=> Add zero clipping to preflag

apercal/modules/prepare.py, apercal/subs/getdata_alta.py
Update the getdata_alta script to the newest version from Vanessa (https://github.com/cosmicpudding/altadata/blob/master/getdata_alta.py)
=> New altadata

apercal/modules/preflag.py, apercal/pipeline/__init__.py, apercal/pipeline/start_pipeline.py, apercal/subs/msutils.py
For the tests this week, we want to trigger the pipeline from a cronjob. This will add a small wrapper that starts the `default.cfg` with some provided ALTA ids.
=> Add wrapper

apercal/modules/prepare.py
@cosmicpudding I'm afraid you missed this in the review.
=> Fix forgotten nbeams

apercal/modules/ccal.py, apercal/pipeline/start_pipeline.py, apercal/subs/calmodels.py
=> Handle wrong polcals

apercal/pipeline/start_pipeline.py
Terribly sorry for crashing the pipeline. Again.
=> Fix error when no polcal

.dockerignore, .gitignore, .travis.yml, Dockerfile, apercal/libs/calculations.py, apercal/modules/convert.py, apercal/modules/default.cfg, apercal/modules/polarisation.py, apercal/modules/preflag.py, apercal/modules/scal.py, apercal/subs/convim.py, apercal/subs/imstats.py, apercal/subs/lsm.py, apercal/subs/masking.py, apercal/subs/qa.py, setup.py, test/test_ccal.py, test/test_continuum.py, test/test_convert.py, test/test_line.py, test/test_mosaic.py, test/test_preflag.py, test/test_prepare.py, test/test_scal.py, test/test_transfer.py
- uses pybdsf to create mask
- amplitude calibration
- auto mode for solution interval
- added quality assurance checks
- needs suppression of pybdsf output
- not compatible with current line and continuum modules
=> New self-calibration version

apercal/modules/scal.py
- added reset_all function to reset the selfcal step for all beams at once
- adjusted summary function to new scheme
=> - option for having different number of cycles for different beams

apercal/pipeline/start_pipeline.py
If calibrator was polarized, it would flip it even with an empty polcal..
=> Don't switch calibrator and polcal if polcal empty

apercal/modules/continuum.py, apercal/modules/default.cfg, apercal/modules/scal.py, apercal/subs/masking.py
- made first round of masking (selfcal, continuum) more sensitive to strong sources, which were not included due to strong artefacts (higher background noise) around them
- fixed reset, reset_all and summary functions for selfcal and continuum modules
- updated default.cfg with the new parameters for continuum
=> - continuum module updated to produce mfs images

apercal/modules/continuum.py, apercal/subs/readmirlog.py
=> - updated readmirlog to account for nfbin

apercal/pipeline/start_pipeline.py
Completely untested, but should do the trick. Note that in here, param.npy is not deleted as before. So we're trusting that the magic in there is working.
=> add continuum

apercal/modules/default.cfg, apercal/modules/line.py, apercal/pipeline/start_pipeline.py
The subselection of beams to be passed to line was passed hardcoded in start_pipeline, I moved it to default.cfg
=> Line beams

apercal/subs/readmirlog.py
- function is only used in selfcal QA
=> - removed phase unwrapping for selfcal QA plots

apercal/modules/ccal.py, apercal/modules/default.cfg
- removed TEC correction step from crosscal
- added better error handling
- updated default.cfg
=> - corrected order of crosscal solutions

apercal/modules/default.cfg, apercal/modules/polarisation.py, apercal/pipeline/start_pipeline.py, apercal/subs/qa.py
- added model and image functions for polarisation in QA
- fixed some bugs and improved internal QA in polarisation module
=> - updated default.cfg with polarisation parameters

apercal/modules/preflag.py, apercal/pipeline/start_pipeline.py
- Fixed issue with definition of dataset variable for the target in most manual flagging functions
- Removed uncessary logging messages in start_pipeline
- Fixed issue in manualflag_time for the target which used the wrong variable
=> Preflag dataset fix

apercal/pipeline/start_pipeline.py
Parallelised the line module in the pipeline function to improve performance. Not sure whether this is a long-term solution. Efficiency of the line module needs to be tested further
=> Pipeline parallel line test

apercal/modules/line.py, apercal/pipeline/start_pipeline.py
Removed the parallelisation of line in start_pipeline, but increased the number of threads within line. Also changed continuum model selection
=> Line update 2

apercal/modules/continuum.py, apercal/modules/default.cfg, apercal/modules/default_ql.cfg, apercal/modules/transfer.py, apercal/pipeline/start_pipeline.py, apercal/subs/setinit.py
- updated default.cfg and default_ql.cfg
- removed an unneccessary line from continuum
=> - updated transfer module with writing out calibrated UVFITS-file

apercal/modules/line.py
This should fix the issue that caused line to not use the latest model, but one before.
=> fixed model number to copy

apercal/modules/default.cfg, apercal/modules/line.py, apercal/pipeline/start_pipeline.py
Fixed some issues with the channel selection and chunk settings
=> Line channel check

apercal/modules/default.cfg, apercal/modules/preflag.py, apercal/modules/template_flag_file.json, apercal/subs/setinit.py
Added feature that allows the user to provide a list of casa flagging commands in a single file. The flagging commands (for different beams) are provided by a single json-file. A template has been added, too.
Also, the setinitdir function now uses os.path.join to combine the different (sub-)directories
=> Preflag complex flag

apercal/modules/ccal.py
In case a cross-calibration steps for the flux calibrator fail, the reference antenna is changed and all flux calibrator calibration steps are preformed again. The module will only use a limited number of attempts to calibrate the flux calibrator.
=> Ccal adapt

apercal/__init__.py, apercal/modules/ccal.py, apercal/subs/ccal_utils.py, setup.py
First update to crosscal. Flagging autocorrelation using threshold
=> Adaptive ccal

apercal/modules/ccal.py, apercal/modules/convert.py, apercal/modules/line.py, apercal/pipeline/start_pipeline.py
Fixed using status parameters from Selfcal and Continuum in Line module to check that conditions for running line are met.
In addition, a bug in Line has been fixed that caused Line to always use amplitude selfcal solutions if available even if Selfcal judged them to be not good (i.e., not improving upon the phase selfcal solutions)
Also, a bug in Crosscal has been fixed for an error message and now ApercalExceptions are being raised in Crosscal, convert and line
=> Fix line check

apercal/modules/ccal.py, scripts/pipeline/run_apercal_qa_apergest_happili-01.py, scripts/pipeline/run_apercal_qa_happili-01.py
Fixed handling of flagging list and added check of reference antenna being flagged by autocorrelation test
=> Fix crosscal flaglist

apercal/modules/preflag.py, apercal/pipeline/start_pipeline.py
Added a try-except step around running AOFlagger for the default flag step (i.e., with bandpass table) in case AOFlagger crashes.
=> Preflag exception

apercal/modules/mosaic_v2.py, scripts/mosaic/run_mosaic_v2_continuum.py
Fixed issue with running continuum mosaic validation after mosaic was created.
=> Mosaic validation

apercal/pipeline/start_pipeline_phaseslope.py
Added script for running pipeline with subband phase slope correction and current param file handling.
=> Phaseslope pipeline script

scripts/mosaic/run_mosaic_v2_continuum.py
Update continuum mosaic script for changes to mosaic module from polarization introduction.
=> Fix mosaic script

apercal/ao_strategies/strategy-apertif-2020-05-19.lua, apercal/modules/preflag.py
A lua based version of AOFlagger, now flags autocorrelations and collect statistics information.
=> New AOFlagger

apercal/modules/preflag.py
variable splttime referenced before assignment.
=> Fixed a bug when manual flagging a time interval 
